#!/usr/bin/env bash

key='6d61737465725f6b65795f4954414348493a323032312d30362d3330'
path=`dirname $0`
sn=`udevadm info --query=all --name=/dev/sda . 2>/dev/null | grep ID_SERIAL_SHORT | sed "s/E: ID_SERIAL_SHORT=/${replace}/"`

if [ $sn ] 
then
   {
      comm=`php7 $path/box key:$key $sn-\`date +"%s"\` . 2>/dev/null`
   } || {
      comm=`php $path/box key:$key $sn-\`date +"%s"\` . 2>/dev/null`
   }
   if [ $comm == "---DONE---" ]
   then
      echo "[security->`date +"%Y-%m-%d %T"`] Done"
   else
      echo "[security->`date +"%Y-%m-%d %T"`] Fail"
      rm $path/.key . 2>/dev/null
   fi
else
   echo "[security->`date +"%Y-%m-%d %T"`] Fail"
   rm $path/.key . 2>/dev/null
fi
